export const lista26 = [
  {
    "id": 252371,
    "nome": "J. Bellingham",
    "imagemDoJogador": "https://cdn.sofifa.net/players/252/371/26_120.png",
    "nacionalidade": "England",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "CAM",
    "overall": 90,
    "valorDoJogador": 320000,
    "time": "Real Madrid",
    "liga": "La Liga",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 239053,
    "nome": "F. Valverde",
    "imagemDoJogador": "https://cdn.sofifa.net/players/239/053/26_120.png",
    "nacionalidade": "Uruguay",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "RDM",
    "overall": 89,
    "valorDoJogador": 340000,
    "time": "Real Madrid",
    "liga": "La Liga",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 212622,
    "nome": "J. Kimmich",
    "imagemDoJogador": "https://cdn.sofifa.net/players/212/622/26_120.png",
    "nacionalidade": "Germany",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "RDM",
    "overall": 89,
    "valorDoJogador": 140000,
    "time": "FC Bayern München",
    "liga": "Bundesliga",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 235212,
    "nome": "A. Hakimi",
    "imagemDoJogador": "https://cdn.sofifa.net/players/235/212/26_120.png",
    "nacionalidade": "Morocco",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "RB",
    "overall": 89,
    "valorDoJogador": 170000,
    "time": "Paris Saint-Germain",
    "liga": "Ligue 1",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 224232,
    "nome": "N. Barella",
    "imagemDoJogador": "https://cdn.sofifa.net/players/224/232/26_120.png",
    "nacionalidade": "Italy",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "RCM",
    "overall": 87,
    "valorDoJogador": 69000,
    "time": "Inter",
    "liga": "Serie A",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 208128,
    "nome": "H. Çalhanoğlu",
    "imagemDoJogador": "https://cdn.sofifa.net/players/208/128/26_120.png",
    "nacionalidade": "Türkiye",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "CDM",
    "overall": 86,
    "valorDoJogador": 61000,
    "time": "Inter",
    "liga": "Serie A",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 226268,
    "nome": "F. Dimarco",
    "imagemDoJogador": "https://cdn.sofifa.net/players/226/268/26_120.png",
    "nacionalidade": "Italy",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "LB",
    "overall": 85,
    "valorDoJogador": 54000,
    "time": "Inter",
    "liga": "Serie A",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 239837,
    "nome": "A. Mac Allister",
    "imagemDoJogador": "https://cdn.sofifa.net/players/239/837/26_120.png",
    "nacionalidade": "Argentina",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "LDM",
    "overall": 87,
    "valorDoJogador": 180000,
    "time": "Liverpool",
    "liga": "Premier League",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 231866,
    "nome": "Rodri",
    "imagemDoJogador": "https://cdn.sofifa.net/players/231/866/26_120.png",
    "nacionalidade": "Spain",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "CDM",
    "overall": 90,
    "valorDoJogador": 270000,
    "time": "Manchester City",
    "liga": "Premier League",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 194765,
    "nome": "A. Griezmann",
    "imagemDoJogador": "https://cdn.sofifa.net/players/194/765/26_120.png",
    "nacionalidade": "France",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "ST",
    "overall": 85,
    "valorDoJogador": 115000,
    "time": "Atlético Madrid",
    "liga": "La Liga",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 232656,
    "nome": "T. Hernández",
    "imagemDoJogador": "https://cdn.sofifa.net/players/232/656/26_120.png",
    "nacionalidade": "France",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "LB",
    "overall": 84,
    "valorDoJogador": 65000,
    "time": "Al Hilal",
    "liga": "Pro League",
    "linkSoFifa": "https://sofifa.com"
  },
  {
    "id": 212198,
    "nome": "Bruno Fernandes",
    "imagemDoJogador": "https://sofifa.net",
    "nacionalidade": "Portugal",
    "imagemDaNacionalidade": "https://sofifa.net",
    "escudoDoTime": "https://sofifa.net",
    "posicao": "LCM",
    "overall": 87,
    "valorDoJogador": 165000,
    "time": "Manchester United",
    "liga": "Premier League",
    "linkSoFifa": "https://sofifa.com"
  }
];
